# Site settings
title: Rubber Duck Club
email: 
description: > # this means to ignore newlines until "baseurl:"
  This will be a blog soon.
baseurl: "/jekyll/" # the subpath of your site, e.g. /blog/
url: "dcrichards.me" # the base hostname & protocol for your site
twitter_username: 
github_username:  DCRichards

# Build settings
markdown: kramdown
